# Generated by Django 4.0 on 2022-04-28 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic2', '0003_skills'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Skills',
            new_name='Skill',
        ),
    ]
