# Generated by Django 4.0 on 2022-04-28 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic2', '0004_rename_skills_skill'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='skill1',
            new_name='skill',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='skill2',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='skill3',
        ),
    ]
