# Generated by Django 4.0 on 2022-04-29 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic2', '0005_rename_skill1_skill_skill_remove_skill_skill2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill1', models.TextField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
