# Generated by Django 4.0.4 on 2022-05-01 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic2', '0006_skill1_delete_skill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill2', models.TextField(max_length=100)),
            ],
        ),
    ]
