# Generated by Django 4.0.4 on 2022-05-01 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic2', '0007_skill2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill3', models.CharField(max_length=100)),
            ],
        ),
    ]
