# Generated by Django 4.0 on 2022-05-10 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic2', '0008_skill3'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='skill1',
            name='skill1',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='skill2',
            name='skill2',
            field=models.CharField(max_length=100),
        ),
    ]
