# Generated by Django 4.0.4 on 2022-05-03 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic2', '0008_skill3'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill4', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='skill1',
            name='skill1',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='skill2',
            name='skill2',
            field=models.CharField(max_length=100),
        ),
    ]
