# Generated by Django 4.0.4 on 2022-05-03 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic2', '0009_skill4_alter_skill1_skill1_alter_skill2_skill2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proj1name', models.CharField(max_length=100)),
                ('proj1desc', models.TextField(max_length=500)),
            ],
        ),
    ]
