# Generated by Django 4.0.4 on 2022-05-03 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic2', '0010_project1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project1',
            old_name='proj1desc',
            new_name='project1',
        ),
        migrations.RemoveField(
            model_name='project1',
            name='proj1name',
        ),
    ]
