# Generated by Django 4.0.4 on 2022-05-17 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic2', '0011_rename_proj1desc_project1_project1_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Project1',
            new_name='Project',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='project1',
            new_name='project',
        ),
    ]
